mcc: '901'          # Mobile Country Code value
mnc: '70'           # Mobile Network Code value (2 or 3 digits)

nci: '0x000000010'  # NR Cell Identity (36-bit)
idLength: 32        # NR gNB ID length in bits [22...32]
tac: 1              # Tracking Area Code

linkIp: 10.0.2.5   # gNB's local IP address for Radio Link Simulation (Usually same with local IP)
ngapIp: 10.0.2.5   # gNB's local IP address for N2 Interface (Usually same with local IP)
gtpIp: 10.0.2.5    # gNB's local IP address for N3 Interface (Usually same with local IP)

# List of AMF address information
amfConfigs:
  - address: 10.0.2.4
    port: 38412

# List of supported S-NSSAIs by this gNB
slices:
  - sst: 1

# Indicates whether or not SCTP stream number errors should be ignored.
ignoreStreamIds: true

intraFreqReselectionAllowed: true

cellSelectionInfo:
  q_RxLevMin: -70 # -70..-22
  q_RxLevMinOffset: 2 # 1..8
  q_RxLevMinSUL: -70 # -70..-22
  q_QualMin: -43 # -43..-12
  q_QualMinOffset: 1 # 1..8

cellReselectionInfo:
  q_Hyst: 8 # {0, 1, 2, 3, 4, 5, 6, 8, 10, ..., 24}
  treshServingLowP: 1 # 0..31
  cellReselectionPriority: 2 # 0..7
  q_RxLevMin: -70
  s_IntraSearchP: 4 # 0..31
  s_IntraSearchQ: 1 # 0..31
  t_ReselectionNR: 1 # 0..7
  deriveSSB_IndexFromCell: false